# Generated by Django 5.1.6 on 2025-04-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0005_alter_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Supplier', 'Supplier'), ('Customer', 'Customer'), ('Staff', 'Staff')], default='Admin', max_length=50, null=True),
        ),
    ]
