# Generated by Django 5.1.6 on 2025-04-21 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0006_alter_users_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
    ]
