# Generated by Django 5.1.6 on 2025-04-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0007_remove_users_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
