# Generated by Django 5.1.6 on 2025-04-21 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0008_users_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
    ]
