# Generated by Django 5.1.6 on 2025-04-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0009_remove_users_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_pic',
            field=models.TextField(blank=True, default='https://example.com/default.jpg', null=True),
        ),
    ]
