# Generated by Django 5.1.6 on 2025-04-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0010_alter_users_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_pic',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
