# Generated by Django 5.1.6 on 2025-05-08 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0012_alter_users_city_alter_users_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_name',
        ),
    ]
