# Generated by Django 5.1.6 on 2025-05-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0015_alter_users_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_name',
        ),
    ]
