# Generated by Django 5.1.6 on 2025-05-19 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0017_users_first_name_users_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_name',
        ),
    ]
