# Generated by Django 5.1.6 on 2025-05-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0018_remove_users_first_name_remove_users_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45)),
                ('cookies', models.JSONField()),
                ('user_agent', models.TextField()),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='users',
            old_name='dob',
            new_name='birthdate',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='activity_date',
        ),
        migrations.RemoveField(
            model_name='users',
            name='departMent',
        ),
        migrations.RemoveField(
            model_name='users',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='users',
            name='domain_name',
        ),
        migrations.AddField(
            model_name='users',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Supplier', 'Supplier'), ('Customer', 'Customer'), ('Staff', 'Staff')], default='Customer', max_length=50, null=True),
        ),
    ]
