# Generated by Django 5.1.6 on 2025-05-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0019_visit_rename_dob_users_birthdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='birthdate',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_device',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_device',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
