# Generated by Django 5.1.6 on 2025-05-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0020_remove_users_birthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
