# Generated by Django 5.1.6 on 2025-05-19 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0021_users_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='state',
        ),
    ]
