# Generated by Django 5.1.6 on 2025-05-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0022_remove_users_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='province',
            field=models.CharField(blank=True, default='Kinshasa', max_length=50, null=True),
        ),
    ]
