# Generated by Django 5.1.6 on 2025-06-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0025_users_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='country',
            field=models.CharField(blank=True, choices=[('Congo', 'Congo'), ('Tanzania', 'Tanzania'), ('Angola', 'Angola'), ('Zambia', 'Zambia'), ('Burundi', 'Burundi'), ('Uganda', 'Uganda'), ('Zimbabwe', 'Zimbabwe'), ('Others', 'Others'), ('Congo-brazza', 'Congo-brazza')], default='Congo', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
