# Generated by Django 5.1.6 on 2025-06-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0026_alter_users_country_alter_users_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
