# Generated by Django 5.1.6 on 2025-06-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0027_alter_users_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
