# Generated by Django 5.1.6 on 2025-06-12 09:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0028_users_first_name_users_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='anon_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='visit',
            name='anon_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
