# Generated by Django 5.1.6 on 2025-06-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0029_users_anon_id_visit_anon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='anon_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='anon_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
