# Generated by Django 5.1.6 on 2025-08-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0032_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='city',
            field=models.CharField(blank=True, default='Lubumbashi', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='province',
            field=models.CharField(blank=True, default='Haut-Katanga', max_length=50, null=True),
        ),
    ]
