# Generated by Django 5.1.6 on 2025-06-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductServices', '0006_alter_categories_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='addition_details',
        ),
        migrations.RemoveField(
            model_name='products',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='products',
            name='brand_model',
        ),
        migrations.RemoveField(
            model_name='products',
            name='color',
        ),
        migrations.RemoveField(
            model_name='products',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='products',
            name='highlights',
        ),
        migrations.RemoveField(
            model_name='products',
            name='html_description',
        ),
        migrations.RemoveField(
            model_name='products',
            name='initial_buying_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='initial_selling_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='products',
            name='seo_keywords',
        ),
        migrations.RemoveField(
            model_name='products',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='products',
            name='specifications',
        ),
        migrations.RemoveField(
            model_name='products',
            name='tax_percentage',
        ),
        migrations.RemoveField(
            model_name='products',
            name='uom',
        ),
        migrations.RemoveField(
            model_name='products',
            name='weight',
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='products',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
