# Generated by Django 5.1.6 on 2025-06-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductServices', '0007_remove_products_addition_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='additionnal_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.FloatField(default=6989.99),
            preserve_default=False,
        ),
    ]
