# Generated by Django 5.1.6 on 2025-06-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductServices', '0008_products_additionnal_details_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='additionnal_details',
            field=models.JSONField(default='[]'),
            preserve_default=False,
        ),
    ]
