# Generated by Django 5.1.6 on 2025-06-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductServices', '0009_alter_products_additionnal_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='additionnal_details',
        ),
        migrations.AddField(
            model_name='products',
            name='additional_details',
            field=models.JSONField(default='[]'),
            preserve_default=False,
        ),
    ]
