# Generated by Django 5.1.6 on 2025-06-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductServices', '0010_remove_products_additionnal_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='additional_details',
        ),
        migrations.AddField(
            model_name='products',
            name='additionnal_details',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
