# Generated by Django 5.1.6 on 2025-06-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductServices', '0011_remove_products_additional_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='city',
            field=models.CharField(default='Kinsahasa', max_length=255),
        ),
    ]
