# Generated by Django 5.1.6 on 2025-06-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductServices', '0012_products_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='city',
            field=models.CharField(default='Kinshasa', max_length=255),
        ),
    ]
