# Generated by Django 5.1.6 on 2025-06-12 09:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductServices', '0013_alter_products_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anon_id', models.UUIDField(default=uuid.uuid4)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(choices=[('like', 'Like'), ('share', 'Share'), ('view', 'View')], max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='ProductServices.products')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ip_address', 'anon_id', 'product', 'action'), ('user', 'ip_address', 'anon_id', 'product', 'action')},
            },
        ),
    ]
