# Generated by Django 5.1.6 on 2025-06-12 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductServices', '0014_productinteraction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinteraction',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='productinteraction',
            name='anon_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productinteraction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductServices.products'),
        ),
        migrations.AlterField(
            model_name='productinteraction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
