# Generated by Django 5.1.6 on 2025-06-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductServices', '0016_alter_productinteraction_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
