# Generated by Django 5.1.6 on 2025-08-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductServices', '0018_alter_products_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='additionnal_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
