# Generated by Django 5.1.6 on 2025-08-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductServices', '0019_alter_products_additionnal_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='like_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='products',
            name='share_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='products',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
