# Generated by Django 5.1.6 on 2025-09-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductServices', '0020_products_like_count_products_share_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='currency',
            field=models.CharField(blank=True, choices=[('CDF', 'CDF'), ('USD', 'USD')], default='CDF', max_length=50, null=True),
        ),
    ]
