# Generated by Django 5.1.6 on 2025-04-23 13:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderServices', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderiteminwardedlog',
            old_name='buy_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='salesorderitemoutwardedlog',
            old_name='buy_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='expected_delivery_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='purchaseorderinwardedlog',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='purchaseorderinwardedlog',
            name='received_at',
        ),
        migrations.RemoveField(
            model_name='purchaseorderinwardedlog',
            name='received_by_user_id',
        ),
        migrations.RemoveField(
            model_name='purchaseorderinwardedlog',
            name='returned_by_user_id',
        ),
        migrations.RemoveField(
            model_name='purchaseorderinwardedlog',
            name='shipping_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseorderinwardedlog',
            name='shipping_cancelled_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseorderinwardedlog',
            name='shipping_cancelled_tax_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseorderinwardedlog',
            name='shipping_cancelled_type',
        ),
        migrations.RemoveField(
            model_name='purchaseorderinwardedlog',
            name='shipping_tax_percentage',
        ),
        migrations.RemoveField(
            model_name='purchaseorderinwardedlog',
            name='shipping_type',
        ),
        migrations.RemoveField(
            model_name='purchaseorderiteminwardedlog',
            name='po_inward_id',
        ),
        migrations.RemoveField(
            model_name='purchaseorderiteminwardedlog',
            name='sell_price',
        ),
        migrations.RemoveField(
            model_name='purchaseorderiteminwardedlog',
            name='shipping_cancelled_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseorderiteminwardedlog',
            name='shipping_cancelled_tax_percentage',
        ),
        migrations.RemoveField(
            model_name='purchaseorderiteminwardedlog',
            name='shipping_cancelled_type',
        ),
        migrations.RemoveField(
            model_name='purchaseorderiteminwardedlog',
            name='shipping_type',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='shipping_cancelled_type',
        ),
        migrations.RemoveField(
            model_name='salesorderitemoutwardedlog',
            name='sell_price',
        ),
        migrations.RemoveField(
            model_name='salesorderitemoutwardedlog',
            name='shipping_cancelled_amount',
        ),
        migrations.RemoveField(
            model_name='salesorderitemoutwardedlog',
            name='shipping_cancelled_tax_percentage',
        ),
        migrations.RemoveField(
            model_name='salesorderitemoutwardedlog',
            name='shipping_cancelled_type',
        ),
        migrations.RemoveField(
            model_name='salesorderitemoutwardedlog',
            name='shipping_type',
        ),
        migrations.RemoveField(
            model_name='salesorderitemoutwardedlog',
            name='so_outwarded_id',
        ),
        migrations.RemoveField(
            model_name='salesorderlogs',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='salesorderoutwardedlog',
            name='returned_at',
        ),
        migrations.RemoveField(
            model_name='salesorderoutwardedlog',
            name='returned_by_user_id',
        ),
        migrations.RemoveField(
            model_name='salesorderoutwardedlog',
            name='send_at',
        ),
        migrations.RemoveField(
            model_name='salesorderoutwardedlog',
            name='send_by_user_id',
        ),
        migrations.RemoveField(
            model_name='salesorderoutwardedlog',
            name='shipping_amount',
        ),
        migrations.RemoveField(
            model_name='salesorderoutwardedlog',
            name='shipping_cancelled_amount',
        ),
        migrations.RemoveField(
            model_name='salesorderoutwardedlog',
            name='shipping_cancelled_tax_amount',
        ),
        migrations.RemoveField(
            model_name='salesorderoutwardedlog',
            name='shipping_cancelled_type',
        ),
        migrations.RemoveField(
            model_name='salesorderoutwardedlog',
            name='shipping_tax_percentage',
        ),
        migrations.RemoveField(
            model_name='salesorderoutwardedlog',
            name='shipping_type',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='last_updated_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_updated_by_user_id_purchase_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='received_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_by_user_id_purchase_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='returned_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returned_by_user_id_purchase_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_cancelled_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_cancelled_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_type',
            field=models.CharField(choices=[('FREE', 'FREE'), ('PAID', 'PAID')], default='FREE', max_length=255),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='approved_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by_user_id_purchase_order_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='cancelled_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancelled_by_user_id_purchase_order_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='cancelled_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='created_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user_id_purchase_order_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='received_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_by_user_id_purchase_order_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='returned_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returned_by_user_id_purchase_order_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='shipping_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='shipping_cancelled_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='shipping_cancelled_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='shipping_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('CREATED', 'CREATED'), ('APPROVED', 'APPROVED'), ('SENT', 'SENT'), ('RECEIVED', 'RECEIVED'), ('PARTIAL RECEIVED', 'PARTIAL RECEIVED'), ('CANCELLED', 'CANCELLED'), ('RETURNED', 'RETURNED'), ('PARITAL RETURNED', 'PARITAL RETURNED')], default='DRAFT', max_length=255),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='updated_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_user_id_purchase_order_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorder',
            name='received_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_by_user_id_sales_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='returned_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorder',
            name='returned_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returned_by_user_id_sales_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesorderorderitems',
            name='approved_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorderorderitems',
            name='approved_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by_user_id_so_order_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderorderitems',
            name='cancelled_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorderorderitems',
            name='cancelled_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancelled_by_user_id_so_order_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderorderitems',
            name='cancelled_reason',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorderorderitems',
            name='created_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user_id_so_order_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderorderitems',
            name='returned_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorderorderitems',
            name='returned_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returned_by_user_id_so_order_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderorderitems',
            name='shipped_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorderorderitems',
            name='shipped_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_by_user_id_so_order_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderorderitems',
            name='shipping_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesorderorderitems',
            name='shipping_cancelled_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesorderorderitems',
            name='shipping_cancelled_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesorderorderitems',
            name='shipping_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesorderorderitems',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('SENT', 'SENT'), ('DELIVERED', 'DELIVERED'), ('PARTIAL DELIVERED', 'PARTIAL DELIVERED'), ('CANCELLED', 'CANCELLED'), ('RETURNED', 'RETURNED'), ('PARITAL RETURNED', 'PARITAL RETURNED')], default='DRAFT', max_length=255),
        ),
        migrations.AddField(
            model_name='salesorderorderitems',
            name='updated_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_user_id_so_order_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='discount_type',
            field=models.CharField(choices=[('PERCENTAGE', 'PERCENTAGE'), ('AMOUNT', 'AMOUNT'), ('NO DISCOUNT', 'NO DISCOUNT')], default='NO DISCOUNT', max_length=255),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('CREATED', 'CREATED'), ('APPROVED', 'APPROVED'), ('SENT', 'SENT'), ('RECEIVED', 'RECEIVED'), ('PARTIAL RECEIVED', 'PARTIAL RECEIVED'), ('CANCELLED', 'CANCELLED'), ('RETURNED', 'RETURNED')], default='DRAFT', max_length=255),
        ),
        migrations.AlterField(
            model_name='purchaseorderinwardedlog',
            name='invoice_path',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='purchaseorderinwardedlog',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('SENT', 'SENT'), ('RECEIVED', 'RECEIVED'), ('PARTIAL RECEIVED', 'PARTIAL RECEIVED'), ('CANCELLED', 'CANCELLED'), ('RETURNED', 'RETURNED')], default='DRAFT', max_length=255),
        ),
        migrations.AlterField(
            model_name='purchaseorderiteminwardedlog',
            name='discount_type',
            field=models.CharField(choices=[('PERCENTAGE', 'PERCENTAGE'), ('AMOUNT', 'AMOUNT')], default='PERCENTAGE', max_length=255),
        ),
        migrations.AlterField(
            model_name='purchaseorderiteminwardedlog',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('SENT', 'SENT'), ('RECEIVED', 'RECEIVED'), ('PARTIAL RECEIVED', 'PARTIAL RECEIVED'), ('CANCELLED', 'CANCELLED'), ('RETURNED', 'RETURNED')], default='DRAFT', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='discount_type',
            field=models.CharField(choices=[('PERCENTAGE', 'PERCENTAGE'), ('AMOUNT', 'AMOUNT')], default='PERCENTAGE', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='shipping_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='shipping_cancelled_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='shipping_cancelled_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='shipping_tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('SENT', 'SENT'), ('DELIVERED', 'DELIVERED'), ('PARTIAL DELIVERED', 'PARTIAL DELIVERED'), ('CANCELLED', 'CANCELLED'), ('RETURNED', 'RETURNED')], default='DRAFT', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesorderitemoutwardedlog',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesorderitemoutwardedlog',
            name='discount_type',
            field=models.CharField(choices=[('PERCENTAGE', 'PERCENTAGE'), ('AMOUNT', 'AMOUNT')], default='PERCENTAGE', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesorderitemoutwardedlog',
            name='shipping_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesorderitemoutwardedlog',
            name='shipping_tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesorderitemoutwardedlog',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('SENT', 'SENT'), ('DELIVERED', 'DELIVERED'), ('PARTIAL DELIVERED', 'PARTIAL DELIVERED'), ('CANCELLED', 'CANCELLED'), ('RETURNED', 'RETURNED')], default='DRAFT', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesorderitemoutwardedlog',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesorderorderitems',
            name='amount_cancelled',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesorderorderitems',
            name='amount_ordered',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesorderorderitems',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesorderorderitems',
            name='amount_returned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesorderorderitems',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesorderorderitems',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesorderorderitems',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesorderorderitems',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesorderoutwardedlog',
            name='invoice_path',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='salesorderoutwardedlog',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('SENT', 'SENT'), ('DELIVERED', 'DELIVERED'), ('PARTIAL DELIVERED', 'PARTIAL DELIVERED'), ('CANCELLED', 'CANCELLED'), ('RETURNED', 'RETURNED')], default='DRAFT', max_length=255),
        ),
    ]
