# Generated by Django 5.1.6 on 2025-04-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderServices', '0003_rename_buy_price_purchaseorderiteminwardedlog_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderiteminwardedlog',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
