# Generated by Django 5.1.6 on 2025-04-23 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderServices', '0004_purchaseorderiteminwardedlog_buy_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderiteminwardedlog',
            name='buy_price',
        ),
    ]
