# Generated by Django 5.1.6 on 2025-04-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderServices', '0007_purchaseorderiteminwardedlog_buy_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderiteminwardedlog',
            name='buy_price',
        ),
        migrations.AddField(
            model_name='purchaseorderiteminwardedlog',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
