# Generated by Django 5.1.6 on 2025-04-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderServices', '0008_remove_purchaseorderiteminwardedlog_buy_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderiteminwardedlog',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseorderiteminwardedlog',
            name='shipping_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseorderiteminwardedlog',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
