# Generated by Django 5.1.6 on 2025-04-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderServices', '0009_alter_purchaseorderiteminwardedlog_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='expected_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_terms',
            field=models.CharField(choices=[('CASH', 'CASH'), ('CREDIT', 'CREDIT'), ('ONLINE', 'ONLINE'), ('CHEQUE', 'CHEQUE')], default='CASH', max_length=255),
        ),
    ]
